### ISSUE TITLE
paper似乎点不开

### ISSUE THREAD

**Issue by coolbeam** [yumingj/C2-Matching#1]
hi，麻烦check一下pdf paper的链接，点进去是您的个人主页，里面的paper链接点进去还是个人主页，是paper暂时没有放出来吗

**Comment by yumingj** [comment]
Hi, our paper has been submitted to arxiv and it is still in processing. It will be public in a few days. We will update the link once it is available in arxiv. Thanks for your interest in our work!

**Comment by coolbeam** [comment]
嘿嘿，谢谢

**Comment by yumingj** [comment]
Hello, the paper link has been updated. Feel free to check out :)
