### ISSUE TITLE
scale

### ISSUE THREAD

**Issue by hbw945** [yumingj/C2-Matching#10]
1. Can scale only be 4? Can it be adjusted to other scales? If so, what codes need to be modified and what should be paid attention to.

2. In the test phase, can I not sample(down) the input?  I adjust the relevant code, but report an error...

I look forward to your reply!

**Comment by yumingj** [comment]
1. Currently we only support 4x super-resolution. It can be extended to other scales but you may need to retrain the network and modify the architecture of the restoration network.
2. I cannot get your question clearly. The downsampling operation is implemented in line 129 of this [file](https://github.com/yumingj/C2-Matching/blob/master/mmsr/data/ref_cufed_dataset.py).

**Comment by hbw945** [comment]
Thank you for your quick reply!
And I mean that at the beginning of the test, the input image will be x4 down-sampled, and then super-resolution through the network, can I not down-sample the input image at the beginning?
