### ISSUE TITLE
Restoration Module

### ISSUE THREAD

**Issue by cheun726** [yumingj/C2-Matching#11]
where is the code of super-resolution Restoration Module？
Which file contains the super-resolution Restoration Module operation？
Can I use another network structure for  super-resolution？
Looking forward to your reply

**Comment by cheun726** [comment]
您好，我没看太懂ref_restoration_arch.py。您可以大致给我解释一下ref_restoration_arch.py的流程吗？麻烦了，谢谢您



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuming ***@***.***&gt;; 
发送时间: 2021年8月27日(星期五) 晚上8:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yumingj/C2-Matching] Restoration Module (#11)





 
Hi, sorry for the late reply.
 
The architecture for the super-restoration module is in ref_restoration_arch.py.
 
You can use another network structure for super-resolution. But you should include the aggregated reference feature in the new super-resolution structure.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cheun726** [comment]
ref_restoration_arch.py。您可以大致给我解释一下ref_restoration_arch.py的流程吗？麻烦了，谢谢您我想更改vgg的激活函数，应该在哪个函数里面修改呀？


------------------ 原始邮件 ------------------
发件人: "Yuming ***@***.***&gt;; 
发送时间: 2021年8月27日(星期五) 晚上8:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yumingj/C2-Matching] Restoration Module (#11)





 
Hi, sorry for the late reply.
 
The architecture for the super-restoration module is in ref_restoration_arch.py.
 
You can use another network structure for super-resolution. But you should include the aggregated reference feature in the new super-resolution structure.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yumingj** [comment]
你好。ref_restoration_arch.py的流程主要是分为两个函数，ContentExtractor和DynamicAggregationRestoration。一个是对LR input图像进行特征提取，另外一个是基于前面得到的matching来对HR图像的VGG特征做融合。

VGG特征提取在这里：https://github.com/yumingj/C2-Matching/blob/fa171ca6707c6f16a5d04194ce866ea70bb21d2b/mmsr/models/archs/corres_generation_arch.py#L116

如果你想改VGG的激活函数的话应该是在这里修改：https://github.com/yumingj/C2-Matching/blob/master/mmsr/models/archs/vgg_arch.py
