### ISSUE TITLE
Failed to replicate the result reported in the paper.

### ISSUE THREAD

**Issue by wdmwhh** [yumingj/C2-Matching#14]
Thanks for sharing your great works. It is an innotative step to construct GT correspondences through perspective transformations and enable the explicit supervision. 
I add some codes to test the performance on Sun80, Urban100 and Manga109。There are no more changes to the released code.
The first line is the result reported in the paper. The second line is tested from the released checkpoint. In the third line, we retrain the model on Stage3. CUFED has significant gain but other datasets all drop. 
![image](https://user-images.githubusercontent.com/38210459/139655585-2394284d-94d7-473f-af1e-1796694174a4.png)

**Comment by yumingj** [comment]
Hi, thanks for your interest in our work!

For the second line, the results reproduced from our checkpoint are consistent with those reported in the paper. For CUFED and WR-SR dataset, the reference image for each input image is provided, so the results are exactly the same as the paper. For Sun80 and Manga109, the choice of reference image would influence the performance. Therefore, you may observe there exists a performance gap.

For the third line, it is common to have some misalignments between the uploaded checkpoint with the retrained one.

**Comment by wdmwhh** [comment]
![image](https://user-images.githubusercontent.com/38210459/139674942-72003935-a547-4ed3-9538-17a828ad35c6.png)
For Sun80, Urban100, and Manga109, the result replicated from the released code is even worse than TTSR-rec. 
And actually, the code had some weird part. 
```json
lr_steps: [72545, 211040]
lr_gamma: 0.1
````
However, the learning rates are exactly constant during training. 
Lastly, thanks for your prompt reply.

**Comment by yumingj** [comment]
Hi,

The results reproduced by our uploaded checkpoint are better than TTSR-rec. For the retraining, I will check the details later and I will update the results here.

**Comment by wdmwhh** [comment]
Hello, how is the verification going? 
I carefully consider the underlying assumption under the correspondence learning. It is that the input image and the reference image are different perspectives in the same scene. On CUFED5, the assumption is nearly right. However, on Sun80, the reference image is only similar semantically to the input image; on Urban100, aiming to test self-similar searching and transferring, the reference image is the low-resolution input image itself; and on Manga109, the reference image is only the same category (manga) as the input image. On these datasets, the assumption is not tenable.
The above is my thought from the retraining and the corresponding visualizations. If possible, we can unearth it further.

**Comment by yumingj** [comment]
I am so sorry that I didn't have time to retrain the network yet. I checked my previous training log. When I was sorting out this codebase, I just tested the performance on the CUFED5 dataset but haven't tested it on other datasets. So I didn't notice that there is a small drop in the performance of other datasets.

Your thoughts are reasonable. On Sun80, Urban100, and Manga109 datasets, there lack of proper reference images. The performance would degrade when the reference image is not so similar to the input image. 

If you have interests, we can have a further discussion (maybe on WeChat?). My email address is yuming002@e.ntu.edu.sg. Since I cannot find your email, can you kindly drop me an email about your WeChat ID?

**Comment by beiyu555** [comment]
> 感谢您分享您的精彩作品。通过透视变换构建 GT 对应关系并启用显式监督是一个注释性步骤。 我添加了一些代码来测试在Sun80、Urban100和Manga109上的性能。发布的代码没有更多的变化。 第一行是论文中报告的结果。第二行是从发布的检查点测试的。在第三行中，我们在 Stage3 上重新训练模型。CUFED 有显着的收益，但其他数据集都下降了。 ![图片](https://user-images.githubusercontent.com/38210459/139655585-2394284d-94d7-473f-af1e-1796694174a4.png)

你好，可以分享一下Sun80测试集吗，谢谢

**Comment by wdmwhh** [comment]
> > 感谢您分享您的精彩作品。通过透视变换构建 GT 对应关系并启用显式监督是一个注释性步骤。 我添加了一些代码来测试在Sun80、Urban100和Manga109上的性能。发布的代码没有更多的变化。 第一行是论文中报告的结果。第二行是从发布的检查点测试的。在第三行中，我们在 Stage3 上重新训练模型。CUFED 有显着的收益，但其他数据集都下降了。 ![图片](https://user-images.githubusercontent.com/38210459/139655585-2394284d-94d7-473f-af1e-1796694174a4.png)
> 
> 你好，可以分享一下Sun80测试集吗，谢谢

Hi, here is the Sun80.
http://cs.brown.edu/~lbsun/SRproj2012/Sun_Hays_SR_scenematches.zip
http://cs.brown.edu/~lbsun/SRproj2012/Sun_Hays_SR_groundtruth.zip
http://cs.brown.edu/~lbsun/SRproj2012/Sun_Hays_SR_input_128pixels.zip
