### ISSUE TITLE
No module named 'mmsr'

### ISSUE THREAD

**Issue by zhh99** [yumingj/C2-Matching#16]
![IMG_20211120_203418](https://user-images.githubusercontent.com/59161865/142726599-29a21a1d-3d7b-4e62-acd7-24ea7b86a23d.jpg)
Hi,this problem how to solve?

**Comment by yumingj** [comment]
You need to set up the environment according to the instructions provided in Readme.

**Comment by ximu1211** [comment]
> 

Hello my gpu is 30 series, can not support cuda10.0, do you have a way to let me successfully with the environment

**Comment by include5636** [comment]
> > 
> 
> Hello my gpu is 30 series, can not support cuda10.0, do you have a way to let me successfully with the environment

Hi, I have solved this problem, you can try my repo https://github.com/include5636/C2-Matching-CUDA11/ if still in need.
