### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by chenmz430** [yumingj/C2-Matching#18]
Cuda 11.1 is ok？

**Comment by yumingj** [comment]
You'd better follow the Cuda version. We haven't tried if Cuda 11.1 is ok.

**Comment by ximu1211** [comment]
> Cuda 11.1 is ok？

Did you solve this problem？I also face the problem that Cuda11 can not match the environment, my 3090 does not support cuda versions below 11

**Comment by yukeyiniupi** [comment]
> > Cuda 11.1 is ok？
> 
> Did you solve this problem？I also face the problem that Cuda11 can not match the environment, my 3090 does not support cuda versions below 11

你好，请问你解决了cuda版本问题了吗？

**Comment by include5636** [comment]
> > Cuda 11.1 is ok？
> 
> Did you solve this problem？I also face the problem that Cuda11 can not match the environment, my 3090 does not support cuda versions below 11

I have solved this problem, you can try my repo https://github.com/include5636/C2-Matching-CUDA11/ if still in need.

**Comment by include5636** [comment]
> > Cuda 11.1 is ok？
> 
> Did you solve this problem？I also face the problem that Cuda11 can not match the environment, my 3090 does not support cuda versions below 11



> > > Cuda 11.1 is ok？
> > 
> > 
> > Did you solve this problem？I also face the problem that Cuda11 can not match the environment, my 3090 does not support cuda versions below 11
> 
> 你好，请问你解决了cuda版本问题了吗？

I have solved this problem, you can try my repo https://github.com/include5636/C2-Matching-CUDA11/ if still in need.
