### ISSUE TITLE
Why resample both original and reference images?

### ISSUE THREAD

**Issue by crameth** [yumingj/C2-Matching#4]
I was looking through `ref_cufed_dataset.py`. Saw under the dataloader that the code downsamples and upsamples both original and reference images:

```
        # downsample image using PIL bicubic kernel
        lq_h, lq_w = gt_h // scale, gt_w // scale
        
        img_in_lq = img_in_pil.resize((lq_w, lq_h), Image.BICUBIC)
        img_ref_lq = img_ref_pil.resize((lq_w, lq_h), Image.BICUBIC)
        
        # bicubic upsample LR
        img_in_up = img_in_lq.resize((gt_w, gt_h), Image.BICUBIC)
        img_ref_up = img_ref_lq.resize((gt_w, gt_h), Image.BICUBIC)
```

I assume we downsample and upsample the images to make them low-resolution, but why do it for the reference image as well? Shouldn't the reference image be high-resolution?

**Comment by yumingj** [comment]
Thanks for your interest in our work!

For reference images, we do only use the high-resolution version for matching and restoration. 

There is no need to downsample and upsample the reference images. And we don't use the downsampled or upsampled reference images in the following procedures. This part of the code is used when implementing other tasks, and for this paper, it is redundant.

**Comment by crameth** [comment]
Thanks for your response!

Do you know where is the code for downsampling the original image (not the reference)?

**Comment by yumingj** [comment]
The downsampling of the original image is in the same file. 

`img_in_lq = img_in_pil.resize((lq_w, lq_h), Image.BICUBIC)`

**Comment by crameth** [comment]
Thanks a lot! Closing this issue.
