### ISSUE TITLE
Hello, thank you for your great work. 

### ISSUE THREAD

**Issue by Sadegh28** [yumingj/C2-Matching#7]

**Comment by Sadegh28** [comment]
Hello, thank you for your great work. I have read your manuscript and the supplementary file. Would you please provide more details about data preprocessing i.e augmentation, scaling, patch sizes and so on.

**Comment by yumingj** [comment]
Hi, 

Thanks for your interest in our work!

In this work, LR images are bicubically downsampled 4 times from HR images.

As for augmentation, when training the contrastive correspondence network, random flip and rotation operations are applied to input images. And then random homography transformation is used to generate paired data and ground-truth correspondences. You can refer to `mmsr/data/contras_dataset.py` for more details. When training restoration network, random flip and rotation operations are applied. You can refer to `mmsr/data/ref_cufed_dataset.py` for more details.

The patch size we used during training is 40 x 40 for LR and 160 x 160 for GT.
