### ISSUE TITLE
Module file

### ISSUE THREAD

**Issue by hbw945** [yumingj/C2-Matching#8]
I'm sorry, please tell me where is the "Dynamic Aggregation Module"?
Looking forward to your reply!

**Comment by yumingj** [comment]
Hi,

The implementation of the Dynamic Aggregation module can be found in [https://github.com/yumingj/C2-Matching/blob/master/mmsr/models/archs/DCNv2/dcn_v2.py](url), the function is `DCN_sep_pre_multi_offset`.

The module is then used in `DynamicAggregationRestoration` of [https://github.com/yumingj/C2-Matching/blob/master/mmsr/models/archs/ref_restoration_arch.py](url).

Thanks.

**Comment by hbw945** [comment]
Thank you!
