### ISSUE TITLE
baseline

### ISSUE THREAD

**Issue by hbw945** [yumingj/C2-Matching#9]
First of all thank you for your work！
Is the baseline in the ablation experiment ssen-rec? 
Looking forward to your reply!

**Comment by yumingj** [comment]
Hi, the baseline in the ablation study is not ssen-rec.

The baseline is constructed by removing the dynamic aggregation module, constrastive correspondence network and correlation distillation component.

The ablation study is performed on GAN models, not reconstruction models.

**Comment by hbw945** [comment]
Thank you for your quick reply！
